export const ELEMENTS = {
    numeroorcamento:'#top-search',
    meusorcamentos:'.busca-atendimentos > :nth-child(1) > input',
    todosorcamentos:'.busca-atendimentos > :nth-child(2)',
    encerrados:':nth-child(3) > input',
    antigos:':nth-child(4) > input',
    buscarorcamento:'#search-form > .btn',
    visualizar:'[data-tooltip="Visualizar "]',

    fazerconferencia:'.bt-conferente-modal > .fa',
    naopossuiobs1:'#is-check0_0',

    opcaoorcamento:'#erros_0_0 > :nth-child(3) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoorcativoincorreto:'[id="erros[0][0][1]"]',
    opcaoorcativonaoselecionado:'[id="erros[0][0][55]"]',
    opcaoorcativofaltando:'[id="erros\[0\]\[0\]\[54\]"]',
    opcaoorcbasexarope:'[id="erros\[0\]\[0\]\[23\]"]',
    opcaoorccalculoposologia:'[id="erros\[0\]\[0\]\[19\]"]',
    opcaoorccapsvegetal:'[id="erros\[0\]\[0\]\[60\]"]',
    opcaoorcconcentracaodiferente:'[id="erros\[0\]\[0\]\[56\]"]',
    opcaoorcdosagemincorreta:'[id="erros\[0\]\[0\]\[2\]"]',
    opcaoorcembalagem:'[id="erros\[0\]\[0\]\[5\]"]',
    opcaoorcexcipienteerrado:'[id="erros\[0\]\[0\]\[72\]"]',
    opcaoorcfilialincorreta:'[id="erros\[0\]\[0\]\[51\]"]',
    opcaoorcformaincorreta:'[id="erros\[0\]\[0\]\[73\]"]',
    opcaoorcformulaaberta:'[id="erros\[0\]\[0\]\[11\]"]',
    opcaoorcformulasfaltando:'[id="erros\[0\]\[0\]\[12\]"]',
    opcaoorcinjetavelvalidadeinferior4meses:'[id="erros\[0\]\[0\]\[121\]"]',
    opcaoorcnomepacienteincorreto:'[id="erros\[0\]\[0\]\[6\]"]',
    opcaoorcorcadocapsulapedecomprimido:'[id="erros\[0\]\[0\]\[68\]"]',
    opcaoorcorcamentodiferente:'[id="erros\[0\]\[0\]\[61\]"]',
    opcaoorcpadronizacaoprescritor:'[id="erros\[0\]\[0\]\[9\]"]',
    opcaoorcprescritorincorreto:'[id="erros\[0\]\[0\]\[7\]"]',
    opcaoorcqsperrado:'[id="erros\[0\]\[0\]\[66\]"]',
    opcaoorcreceitailegivel:'[id="erros\[0\]\[0\]\[62\]"]',
    opcaoorcsemtitulo:'[id="erros\[0\]\[0\]\[114\]"]',
    opcaoorctempotratamentomaiorvalidade:'[id="erros\[0\]\[0\]\[109\]"]',
    opcaoorctipocapsula:'[id="erros\[0\]\[0\]\[3\]"]',
    opcaoorcvarejoorcadoerrado:'[id="erros\[0\]\[0\]\[53\]"]',
    opcaoorcvarejoorcadosemprescritor:'[id="erros\[0\]\[0\]\[52\]"]',
    opcaoorcvolumedoseerrado:'[id="erros\[0\]\[0\]\[71\]"]',
    
    opcaobackoffice:'#erros_0_0 > :nth-child(5) > .ibox-title > .ibox-tools > .collapse-link',
    opcaobackclientecienteativoemfalta:'[id="erros\[0\]\[0\]\[112\]"]',
    opcaobacknaoinformadoformulanaoatendida:'[id="erros\[0\]\[0\]\[116\]"]',
    opcaobackorcamentoenviadoerrado:'[id="erros\[0\]\[0\]\[115\]"]',
    opcaobackreceitavencida:'[id="erros\[0\]\[0\]\[63\]"]',

    opcaoatdn:'#erros_0_0 > :nth-child(7) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoatndaromadif:'[for="erros[0][0][108]"]',
    opcaoatndconfformafarmaceutica:'[for="erros[0][0][113]"]',
    opcaoatndcontroladosemreceita:'[for="erros[0][0][21]"]',
    opcaoatndenvioenderecoerrado:'[for="erros[0][0][111]"]',
    opcaoatndformulafechada:'[for="erros[0][0][69]"]',
    opcaoatndformulanaoorcada:'[for="erros[0][0][119]"]',
    opcaoatndmonitoramento:'[for="erros[0][0][10]"]',
    opcaoatndnumrepeticaoincorreta:'[for="erros[0][0][38]"]',
    opcaoatndpacientecrianca:'[for="erros[0][0][117]"]',
    opcaoatndsemautorizacao:'[for="erros[0][0][15]"]',
    opcaoatndtempodetratamento:'[for="erros[0][0][8]"]',

    opcaoinclusao:'#erros_0_0 > :nth-child(9) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoinclusaofaltoucarimbo:'[for="erros[0][0][22]"]',
    opcaoinclusaofichahorarioerrado:'[for="erros[0][0][45]"]',
    opcaoinclusaofichasemcarimbo:'[for="erros[0][0][46]"]',
    opcaoinclusaoformnaofoiinclusa:'[for="erros[0][0][44]"]',
    opcaoinclusaonaoaddinfos:'[for="erros[0][0][48]"]',
    opcaoinclusaonaoescaneouanexo:'[for="erros[0][0][47]"]',
    opcaoinclusaonaoveiorotulo:'[for="erros[0][0][43]"]',
    opcaoinclusaorotulocortado:'[for="erros[0][0][39]"]',
    opcaoinclusaorotulonaoestapadrao:'[for="erros[0][0][36]"]',
    opcaoinclusaorotuloaromaincorreto:'[for="erros[0][0][42]"]',
    opcaoinclusaorotuloativoerrado:'[for="erros[0][0][27]"]',
    opcaoinclusaorotuloativoforapadrao:'[for="erros[0][0][118]"]',
    opcaoinclusaorotuloconcentracaoerrada:'[for="erros[0][0][28]"]',
    opcaoinclusaorotuloerroortografia:'[for="erros[0][0][40]"]',
    opcaoinclusaorotulofaltainformacao:'[for="erros[0][0][41]"]',
    opcaoinclusaorotulopacientenomeerrado:'[for="erros[0][0][31]"]',
    opcaoinclusaorotuloposologiaerrada:'[for="erros[0][0][30]"]',
    opcaoinclusaorotuloprescritorincorreto:'[for="erros[0][0][32]"]',
    opcaoinclusaorotulosqperrado:'[for="erros[0][0][34]"]',
    opcaoinclusaorotulotituloformula:'[for="erros[0][0][29]"]',
    opcaoinclusaorotulousoerrado:'[for="erros[0][0][37]"]',
    opcaoinclusaorotulovalidadeerrada:'[for="erros[0][0][33]"]',
    opcaoinclusaorotulovolumeerrado:'[for="erros[0][0][35]"]',
    opcaoinclusaorotulotrocado:'[for="erros[0][0][80]"]',

    opcaoconfentrada:'#erros_0_0 > :nth-child(11) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoconfentralteracaoincorretaorcamento:'[for="erros[0][0][102]"]',
    opcaoconfentrfichasemcarimbo:'[for="erros[0][0][90]"]',
    opcaoconfentrforcouerradonaficha:'[for="erros[0][0][83]"]',
    opcaoconfentrnaoaddobsnaficha:'[for="erros[0][0][89]"]',
    opcaoconfentrnaoalterourotulo:'[for="erros[0][0][103]"]',
    opcaoconfentrnaocolocouobsfcerta:'[for="erros[0][0][84]"]',
    opcaoconfentrnaoveiocapsulacorreta:'[for="erros[0][0][82]"]',
    opcaoconfentrobsnareceita:'[for="erros[0][0][16]"]',
    opcaoconfentrrotuloalterado:'[for="erros[0][0][122]"]',

    opcaolab:'#erros_0_0 > :nth-child(13) > .ibox-title > .ibox-tools > .collapse-link',
    opcaolabblisterforapadrao:'[for="erros[0][0][79]"]',
    opcaolabcapsincorreta:'[for="erros[0][0][75]"]',
    opcaolabembalagemincorreta:'[for="erros[0][0][74]"]',
    opcaolabequivocoinfoqtd:'[for="erros[0][0][76]"]',
    opcaolabfaltainfoficha:'[for="erros[0][0][95]"]',
    opcaolabfaltouetiquetas:'[for="erros[0][0][92]"]',
    opcaolabfaltouseringa:'[for="erros[0][0][98]"]',
    opcaolabfichapesagemsemass:'[for="erros[0][0][94]"]',
    opcaolabfrascovazando:'[for="erros[0][0][77]"]',
    opcaolabinfocapsilegivel:'[for="erros[0][0][97]"]',
    opcaolabuniformidadecaps:'[for="erros[0][0][99]"]',
    
    opcaoconfsaida:'#erros_0_0 > :nth-child(15) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoconfsaidachocogomafurou:'[for="erros[0][0][106]"]',
    opcaoconfsaidafracopotequebrou:'[for="erros[0][0][105]"]',

    opcaoexpedicao:'#erros_0_0 > :nth-child(17) > .ibox-title > .ibox-tools > .collapse-link',
    opcaoexpedicaonaoenviadoformula:'#collapseObservacoes0_8 > .feed-activity-list > label',

    registrarconferencia:'#btnSubmitConferencia',
    
}
  