export const ELEMENTS = {
    expandirpainelfiltrosbackoffice:'#leftHeadFilter > .fa',
    acessarbackoffice:':nth-child(4) > [href=""] > .arrow',
    acessarbackofficeemandamento:'ul li ul li a',

    filtrodatainicialreceita:'#filterBackoffice > :nth-child(2) > :nth-child(1) > .form-group > .form-control',
    procurarorcamentobackoffice:'.col-xs-12 > .btn',
    datainicialbackoffice:'2023-01-01T00:00',

    opcaoorcativoincorreto:'[id="erros[0][0][1]"]',
    opcaoorcativonaoselecionado:'[id="erros[0][0][55]"]',
    opcaoorcativofaltando:'[id="erros\[0\]\[0\]\[54\]"]',
    opcaoorcbasexarope:'[id="erros\[0\]\[0\]\[23\]"]',
    opcaoorccalculoposologia:'[id="erros\[0\]\[0\]\[19\]"]',
    opcaoorccapsvegetal:'[id="erros\[0\]\[0\]\[60\]"]',
    opcaoorcconcentracaodiferente:'[id="erros\[0\]\[0\]\[56\]"]',
    opcaoorcdosagemincorreta:'[id="erros\[0\]\[0\]\[2\]"]',
    opcaoorcembalagem:'[id="erros\[0\]\[0\]\[5\]"]',
    opcaoorcexcipienteerrado:'[id="erros\[0\]\[0\]\[72\]"]',
    opcaoorcfilialincorreta:'[id="erros\[0\]\[0\]\[51\]"]',
    opcaoorcformaincorreta:'[id="erros\[0\]\[0\]\[73\]"]',
    opcaoorcformulaaberta:'[id="erros\[0\]\[0\]\[11\]"]',
    opcaoorcformulasfaltando:'[id="erros\[0\]\[0\]\[12\]"]',
    opcaoorcinjetavelvalidadeinferior4meses:'[id="erros\[0\]\[0\]\[121\]"]',
    opcaoorcnomepacienteincorreto:'[id="erros\[0\]\[0\]\[6\]"]',
    opcaoorcorcadocapsulapedecomprimido:'[id="erros\[0\]\[0\]\[68\]"]',
    opcaoorcorcamentodiferente:'[id="erros\[0\]\[0\]\[61\]"]',
    opcaoorcpadronizacaoprescritor:'[id="erros\[0\]\[0\]\[9\]"]',
    opcaoorcprescritorincorreto:'[id="erros\[0\]\[0\]\[7\]"]',
    opcaoorcqsperrado:'[id="erros\[0\]\[0\]\[66\]"]',
    opcaoorcreceitailegivel:'[id="erros\[0\]\[0\]\[62\]"]',
    opcaoorcreceitasemobs:'[id="erros\[0\]\[0\]\[16\]"]',
    opcaoorcsemtitulo:'[id="erros\[0\]\[0\]\[114\]"]',
    opcaoorctempotratamentomaiorvalidade:'[id="erros\[0\]\[0\]\[109\]"]',
    opcaoorctipocapsula:'[id="erros\[0\]\[0\]\[3\]"]',
    opcaoorcvarejoorcadoerrado:'[id="erros\[0\]\[0\]\[53\]"]',
    opcaoorcvarejoorcadosemprescritor:'[id="erros\[0\]\[0\]\[52\]"]',
    opcaoorcvolumedoseerrado:'[id="erros\[0\]\[0\]\[71\]"]',
    opcaobackoffice:':nth-child(5) > .ibox-title > .ibox-tools > .collapse-link > .fa',
    opcaobackclientecienteativoemfalta:'[id="erros\[0\]\[0\]\[112\]"]',
    opcaobacknaoinformadoformulanaoatendida:'[id="erros\[0\]\[0\]\[116\]"]',
    opcaobackorcamentoenviadoerrado:'[id="erros\[0\]\[0\]\[115\]"]',
    opcaobackreceitavencida:'[id="erros\[0\]\[0\]\[63\]"]',
    numeroorcamento:'#top-search',
    meusorcamentos:'.busca-atendimentos > :nth-child(1) > input',
    todosorcamentos:'.busca-atendimentos > :nth-child(2) > input',
    encerrados:':nth-child(3) > input',
    antigos:':nth-child(4) > input',
    buscarorcamento:'#search-form > .btn',
    visualizar:'[a > href="/atendimentos/edit/2109135"] > .fa',
    acessarbackofficeencerrado:'.active > .nav > :nth-child(2) > a',
    fazerconferencia:':nth-child(3) > :nth-child(5) > .bt-conferente-modal > .fa',
    naopossuiobs:'#is-check0_0',
    opcaoorcamento:'#erros_0_0 > .ibox > .ibox-title > .ibox-tools > .collapse-link > .fa',
    registrarconferencia:'#btnSubmitConferencia',
}
  