import { ELEMENTS } from './elements';
const el = ELEMENTS;



/// <reference types="cypress" />
class Atendimento{
  acessarorcamentoAtendimento(){
    cy.get(el.todosorcamentos)
      .should('be.visible')
      .check()
      .should('be.checked')
    cy.get(el.numeroorcamento)
      .should('be.visible')
      .invoke('{enter}')//insere o numero do orcamento e aperta enter
      .should('have.value','')
      .clear()
      .should('have.value','')
      .invoke('val','{enter}')//insere o numero do orcamento e aperta enter
      .should('have.value','')
    cy.get(el.buscarorcamento)
      .should('be.visible')
      .click()
    cy.get(el.visualizar)
      .should('be.visible')
      .click()
      cy.pause()
      
    
      
  }

  sugestaoformulacertaAtendimento(){
    cy.get(el.sugestaoformulacerta)
      .should('be.visible')
      .click()
    cy.get(el.cancelarsugestaoformulacerta)
      .should('be.visible')
      .click()
    
  }

  loghistoricoAtendimento(){
    cy.get(el.acessarlog)
      .should('be.visible')
      .click()
    cy.get(el.cancelarlog)
      .should('be.visible')
      .click()
  }

  dadosclienteAtendimento(){
    cy.contains('Dados Cliente')
      .should('be.visible')
      .click()
    cy.get(el.abageral)
      .should('be.visible')
      .click()
    cy.get(el.abaendereco)
      .should('be.visible')
      .click()
    cy.get(el.abainternet)
      .should('be.visible')
      .click()
    cy.get(el.abaobsfcerta)
      .should('be.visible')
      .click()
    cy.get(el.abaobsmedicopaciente)
      .should('be.visible')
      .click()
    cy.get(el.buscapacienteabaobsmedicopaciente)
      .should('be.visible')
      .type('Paciente')
      .should('have.value' , 'Paciente')
    cy.get(el.buscamedicoabaobsmedicopaciente)
      .should('be.visible')
      .type('Medico')
      .should('have.value' , 'Medico')
    cy.get(el.fechardadoscliente)
      .should('be.visible')
      .click()
  }

  observacaopacientemedicoAtendimento(){
    cy.get(el.acessarobspacientemedico)
      .should('be.visible')
      .click()
    cy.get(el.pesquisapaciente)
      .should('be.visible')
      .type('Busca paciente')
      .should('have.value' , 'Busca paciente')
    cy.get(el.pesquisamedico)
      .should('be.visible')
      .type('Busca medico')
      .should('have.value' , 'Busca medico')
    cy.get(el.fecharobspacientemedico)
      .should('be.visible')
      .type('{esc}')
      .should('not.be.visible')
      
  }

  apontarerroAtendimento(){
    cy.get(el.acessarapontarerro)
      .should('be.visible')
      .click()
    cy.get(el.ok)
      .should('be.visible')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.orcamento)
      .should('be.visible')
      .click()
    cy.get(el.ativoincorreto)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativonaoselecionado)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativofaltando)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativobasexarope)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativocalculoposologia)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativocapsvegetal)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoconcentracaodiferente)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativodosagemincorreta)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoembalagem)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoexcipientebaseerrado)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativofilialincorreta)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativofarmaceuticaincorreta)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoformulaaberta)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoformulafaltando)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoinjetavelcientevalidade)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativonomeclienteincorreto)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoorcadocapsulareceita)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoorcamentodiferente)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativopadronizacaoprescritor)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoprescritorincorreto)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoqsperrado)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativoreceitailegivel)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativosemtitulo)
      .should('be.visible')
      .dblclick({force: true})
    cy.get(el.ativotempomaior)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativotipocapsula)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativovarejoorcadoerrado)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativovarejoorcadov)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.ativodoseerrado)
      .should('be.visible')
      .check()
      .should('be.checked')
      .uncheck()
      .should('not.be.checked')
    cy.get(el.backoffice)
      .should('be.visible')
      .click()
    cy.get(el.clientecienteativofalta)
      .should('be.visible')
      .dblclick({force: true})
      .should('not.be.checked')
    cy.get(el.naoinformadoformula)
      .should('be.visible')
      .dblclick({force: true})
      .should('not.be.checked')
    cy.get(el.enviadocontatoerrado)
      .should('be.visible')
      .dblclick({force: true})
      .should('not.be.checked')
    cy.get(el.receitavencida)
      .should('be.visible')
      .dblclick({force: true})
      .should('not.be.checked')
    cy.get(el.registrar)
      .should('be.visible')
      .click()
  }

  inserirobservacaoAtendimento(){

    // for (let ioa = 1,i = 1 ; ioa <= 36,i <=36 ; ioa++,i++){
    //   cy.get(el.selecionarobsatendimento)
    //     .should('be.visible')
    //     .select(ioa)
    //     .should('exist')
      
    //   cy.get(el.salvarobsatendimento)
    //     .should('be.visible')
    //     .click()
    //   cy.get(el.sucessmessage)
    //     .should('be.visible')
    //     .click()
      
    // }
    cy.get(el.apagarobsatendimento1)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()
    
    cy.get(el.apagarobsatendimento2)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento3)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento4)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento5)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento6)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento7)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento8)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento9)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento10)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento11)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento12)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento13)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento14)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento15)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento16)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento17)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento18)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento19)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento20)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento21)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento22)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento23)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento24)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento25)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento26)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()
    cy.get(el.apagarobsatendimento27)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento28)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento29)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento30)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento31)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento32)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
    .should('be.visible')
    .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento33)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()
    
    cy.get(el.apagarobsatendimento34)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento35)
      .should('be.visible') 
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()

    cy.get(el.apagarobsatendimento36)
      .should('be.visible')
      .click()
    cy.get(el.okapagarobsatendimento)
      .should('be.visible')
      .click()
    cy.get(el.sucessmessage)
      .should('be.visible')
      .click()
      cy.pause()
    
  }

  inseriroutrainformaçãoAtendimento(){
    for (let i = 1 ; i <=5 ; i++){
      cy.get(el.outrainformacao).type('Teste')
      cy.get(el.salvaroutrainformacao).click()
      cy.get(el.sucessmessage).click()
    }
    cy.get(el.apagarobsatendimento1).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento2).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento3).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento4).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento5).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento6).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento7).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento8).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento9).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento10).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento11).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento12).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento13).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento14).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento15).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento16).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento17).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento18).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento19).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento20).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento21).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento22).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento23).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento24).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento25).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento26).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento27).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento28).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento29).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento30).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento31).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento32).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento33).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()
    
    cy.get(el.apagarobsatendimento34).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento35).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()

    cy.get(el.apagarobsatendimento36).click()
    cy.get(el.okapagarobsatendimento).click()
    cy.get(el.sucessmessage).click()
    
  }

  sincronizarAtendimento(){
    cy.get(el.sincronizaratendimento).click()
    cy.wait(10000)
  }

  acompanharpedidotrackingAtendimento(){
    
    cy.visit('http://sm-hkm.local/atendimentos/edit/1966914')
    cy.contains('a','Clique aqui para acompanhar os pedidos deste cliente')
      .should('be.visible')
      .invoke('removeAttr','target')
      .click()
    cy.contains('class="form-group" a','Visualizar')
      .should('be.visible')
      .invoke('removeAttr','target')
      .click()
    cy.url().should('be.equal',`${Cypress.config('baseUrl')}/`)
    // cy.get(el.resultadosporpaginatracking).select(2)
    // cy.get(el.atualizartracking).click()
    // cy.get(el.pesquisartracking).type('5297')
    // cy.get(el.visualizartracking).click()
    // cy.get(el.pagemeusorcamentos).click()
  
    // cy.get(el.acessartrackcingatendimento).click()
  
  }

  prepararemailAtendimento(){
    cy.get(el.acessarprepararemailatendimento).click()
    cy.wait(50000)
    cy.get(el.emailpara).clear()
    cy.get(el.emailpara).type('jose.djalma@essentia.com.br')
    cy.get(el.emailassunto).clear()
    cy.get(el.emailassunto).type('Assunto TESTE')
    cy.contains('input','Enviar').click()
  }

  prepararwhatsappAtendimento(){
    cy.get(el.acessarprepararwhatsappatendimento).click()
    cy.wait(5000)
    cy.get(el.paranumerowhats).type('jose.djalma@essentia.com.br')
    cy.get(el.mensagemwhatsapp).type('Automatizando processos')
    cy.get(el.personalizoumensagemwhats).click()
    cy.get(el.copiarmensagemwhats).click()
    cy.get(el.okcopiarmensagemwhats).click()
    cy.get(el.sucessmessage).click()
    
  }
  prepararlinkavaliacaoAtendimento(){
    cy.get(el.acessavaliacaoatendimento).click()
    cy.get(el.linkavaliacao).click()
    cy.get(el.mensagemlinkavaliacao).type('Automatizando o Processo')
    cy.get(el.copiarmensagemlinkavaliacao).click()
    cy.get(el.fecharlinkavaliacao).click()
  }

  creditooudebitoAtendimento(){
    cy.get(el.acessadicionarcreditoatendimento).click()
    cy.get(el.creditoatendimento).clear()
    cy.get(el.creditoatendimento).type('25')
    cy.get(el.aplicarcredito).click()
    cy.get(el.acessaplicardebitoatendimento).click()
    cy.get(el.debitoatendimento).clear()
    cy.get(el.debitoatendimento).type('25')
    cy.get(el.aplicardebitoatendimento).click()
  }

  trocarresponsavelAtendimento(){
    cy.get(el.acesstrocarresponsavelatendimento).clear()
    cy.get(el.acesstrocarresponsavelatendimento).type('Administrador{downarrow}{enter}')
    cy.wait(5000)
    cy.get(el.acesstrocarresponsavelatendimento).type('{downarrow}{enter}')
  }

  gerarpagamentoAtendimento(){
    cy.get(el.acessgerarpagamentoatendimento).click()
    cy.wait(30000)
    cy.get(el.paragerarpagamento).clear()
    cy.get(el.paragerarpagamento).type('jose.djalma@essentia.com.br')
    cy.get(el.assuntogerarpagamento).clear()
    cy.get(el.assuntogerarpagamento).type('Automatizando o processo')
    cy.get(el.linkcreditogerarpagamento).click()
    cy.get(el.processarpedidogerarpagamento).click()
    cy.get(el.linkpixgerarpagamento).click()
    cy.get(el.processarpedidogerarpagamento).click()
    cy.get(el.enviaremailgerarpagamento).click()
    cy.get(el.sucessmessage).click()
  }

  confirmarAtendimento(){
    cy.get(el.orcamentista).click()
    cy.get(el.orcamentista).clear()
    cy.get(el.orcamentista).type('Amanda{downarrow}{enter}',{delay: 1500})
    cy.get(el.tempotratamento).click()
    cy.wait(5000)
    { if(cy.get(el.inserirtempotratamento)){
      cy.get(el.inserirtempotratamento).clear()
      cy.get(el.inserirtempotratamento).type('30')
      cy.get(el.salvartempotratamento).click()
      cy.get(el.sucessmessage).click()
    }
    else{
      cy.get(el.cancelartempotratamento).click()
    }}
    cy.get(el.acessconfirmaratendimento).click()
    cy.wait(3000)
    cy.get(el.formapagamento).select(5)
    cy.get(el.orcamentoescolhido).click()
    cy.get(el.tempopacientepoderepetir).clear()
    cy.get(el.tempopacientepoderepetir).type('0')
    cy.get(el.salvarformapagamentorepeticao).click()
    cy.wait(10000)
    cy.get(el.canalfechamentopedido).select(3)
    cy.get(el.enviaremailrastreamento).click()
    cy.get(el.liberarpedidoinclusao).click()
    cy.get(el.liberarpedidocaixa).click()
    cy.get(el.obscaixabalcao).clear()
    cy.get(el.obscaixabalcao).type('Automatizando')
    cy.get(el.notadetalhada).click()
    cy.get(el.pago).click()
    cy.get(el.endereco).click({ multiple: true })
    cy.get(el.obsexpedicao).clear()
    cy.get(el.obsexpedicao).type('AUTOMATIZANDO')
    cy.get(el.formaenvio).select(15)
    cy.get(el.juntocomhigashi).click()
    cy.get(el.prometidopara).dblclick()
    cy.get(el.aromashake).select(1)
    cy.get(el.aromacaps).select(1)
    cy.get(el.obsgerais).clear()
    cy.get(el.obsgerais).type('AUTOMATIZANDOOOOOO')
    cy.get(el.possuireceita).click()
    cy.get(el.pedidourgente).click()
    cy.get(el.previsualizar).click()
    cy.wait(20000)
    cy.get(el.fecharprevisualizar).click()
    cy.get(el.salvarpreencheramarelinha).click()
    cy.get(el.sucessmessage).click()
  }

  encerrarAtendimento(){
    cy.contains('Encerrar').click()
    for (var i = 0 ; i <=23 ; i++){
      cy.get(el.opcaoencerraratendimento).select((i))
      cy.get(el.motivoencerraratendimento).type('Opção n°')
      cy.get(el.salvarencerraratendimento).click()
      cy.get(el.sucessmessage).click()
    } 
  }
}

export default new Atendimento()