export enum BudgetConfirmationShippingMethod {
    CounterHkm = "Balcão HKM",
    CounterSmart = "Balcão SMART",
    PostalFree = "Correios - Envio Grátis",
    International = "Correios - Internacional",
    Sedex10 = "Correios - Sedex 10",
    Sedex10Courtesy = "Correios - Sedex 10 CORTESIA",
    Sedex12 = "Correios - Sedex 12",
    Sedex12Courtesy = "Correios - Sedex 12 Cortesia",
    SedexFloripa = "Correios - Sedex Floripa",
    SedexOtherStates = "Correios - Sedex OUTROS ESTADOS",
    SedexSc = "Correios - Sedex SC",
    AirShipping = "Envio Aéreo",
    ShippingPeMt = "Envio PE e MT",
    ShippingPeMtFree = "Envio PE e MT grátis",
    ExpeditionHkm = "Expedição HKM",
    ExpeditionSmart = "Expedição SMART",
    EmployeePickup = "Funcionário - Retirada Recepção",
    EmployeeSedex = "Funcionário - Sedex",
    Delivery = "Tele-entrega",
    CarrierQuality = "Transportadora - Quality",
    CarrierQualityFree = "Transportadora - Quality (Grátis)",
}
