export enum BudgetConfirmationPaymentMethod {
    VisitArrangement = "10",
    ArrangementVisitSpreadsheet = "14",
    BankSlip = "2",
    BankSlipReleaseWithoutPayment = "9",
    PatientBankSlipBox = "3",
    PrescriberBankSlipBox = "13",
    InstallmentBankSlip = "15",
    CreditCard = "1",
    GpeCardAwaitingPayment = "11",
    GpeCardReleaseWithoutPayment = "12",
    Check = "7",
    Courtesy = "5",
    Deposit = "4",
    Cash = "6",
    Other = "8",
    Pix = "16",
}