export enum BudgetConfirmationShippingMethod {
    SedexSC = '1',
    SedexOtherStates = '2',
    Sedex10 = '3',
    Sedex10Courtesy = '4',
    FreeSedexShipping = '5',
    International = '6',
    CenterCounter = '7',
    Delivery = '8',
    SedexFloripa = '9',
    HKMCounter = '10',
    Air = '11',
    ShippingQuality = '12',
    ShippingQualityFree = '13',
    HKMExpedition = '14',
    SMARTExpedition = '15',
    SedexToday = '16',
}