export enum CapsuleAroma {
    SelectAroma = 'Selecione o Aroma',
    Pineapple = 'Abacaxi',
    StandardBaseAroma = 'Aroma da base padrão',
    Vanilla = 'Baunilha',
    Cocoa = 'Cacau',
    Raspberry = 'Raspberry',
    Orange = 'Orange',
    OrangeWithMintAndSpearmint = 'Orange com hortelã/menta',
    Lemon = 'Limão',
    MintSpearmint = 'Menta/hortelã',
    Strawberry = 'Morango',
    NoAroma = 'Sem aroma',
    Grape = 'Uva',
}
