export enum Profile {
    All = 'Todos',
    Viewer = '0',
    ControlRecipes = '2',
    Attendant = '3',
    Expedition = '4',
    Box = '5',
    Administrator = '6',
    Pharmaceutical = '7',
    Budgetist = '8',
    Operator = '9',
    Visitation = '10',
    Marketing = '11',
    Reception = '12',
    Training = '13',
    Inclusion = '14',
    FinancialControl = '15',
    Conference = '16',
    Warehouse = '17',
    PharmaceuticalConferenceOutput = '18',
    Backoffice = '19',
    Laboratory = '20',
    Monitor = '21',
}