export const ELEMENTS = {
    numeroorcamento:'#top-search',
    meusorcamentos:'input[type="radio"]',
    todosorcamentos:'input[type="radio"]',
    encerrados:':nth-child(3) > input',
    antigos:':nth-child(4) > input',
    buscarorcamento:'#search-form > .btn',
    visualizar:'.visualizarFvc > .fa',

    sugestaoformulacerta:'#creditoSearchFcBtn',
    cancelarsugestaoformulacerta:'#findFormulaCertaModal > .modal-dialog > .modal-content > .modal-footer > .btn',

    acessarlog:'#creditoLogBtn',
    cancelarlog:'#logCreditoModal > .modal-dialog > .modal-content > .modal-footer > .btn',

    acessardadoscliente:'',
    abageral:'[role="tabpanel"] > .nav > .active > a',
    abaendereco:'[role="tabpanel"] > .nav > :nth-child(2) > a',
    abainternet:'[role="tabpanel"] > .nav > :nth-child(3) > a',
    abaobsfcerta:'[role="tabpanel"] > .nav > :nth-child(4) > a',
    abaobsmedicopaciente:'[role="tabpanel"] > .nav > :nth-child(5) > a',
    buscapacienteabaobsmedicopaciente:':nth-child(1) > .ibox-title > .search-term',
    buscamedicoabaobsmedicopaciente:':nth-child(2) > .ibox-title > .search-term',
    fechardadoscliente:'#modalDadosCliente > .modal-dialog > .modal-content > .modal-header > .close > span',

    acessarobspacientemedico:'#bt-visualizar-modal',
    pesquisapaciente:'#modal-placeholder-lg-content > .wrapper > :nth-child(1) > .ibox-title > .search-term',
    pesquisamedico:'#modal-placeholder-lg-content > .wrapper > :nth-child(2) > .ibox-title > .search-term',
    fecharobspacientemedico:'#modal-placeholder-lg > .modal-dialog',

    acessarapontarerro:'.bt-conferente-modal',
    ok:'#is-check2109018',
    orcamento:':nth-child(3) > .ibox-title > .ibox-tools > .collapse-link',
    ativoincorreto:'.feed-activity-list > [value="1"]',
    ativonaoselecionado:'.feed-activity-list > [value="55"]',
    ativofaltando:'.feed-activity-list > [value="54"]',
    ativobasexarope:'.feed-activity-list > [value="23"]',
    ativocalculoposologia:'.feed-activity-list > [value="19"]',
    ativocapsvegetal:'.feed-activity-list > [value="60"]',
    ativoconcentracaodiferente:'.feed-activity-list > [value="56"]',
    ativodosagemincorreta:'.feed-activity-list > [value="2"]',
    ativoembalagem:'.feed-activity-list > [value="5"]',
    ativoexcipientebaseerrado:'.feed-activity-list > [value="72"]',
    ativofilialincorreta:'.feed-activity-list > [value="51"]',
    ativofarmaceuticaincorreta:'.feed-activity-list > [value="73"]',
    ativoformulaaberta:'.feed-activity-list > [value="11"]',
    ativoformulafaltando:'.feed-activity-list > [value="12"]',
    ativoinjetavelcientevalidade:'.feed-activity-list > [value="121"]',
    ativonomeclienteincorreto:'.feed-activity-list > [value="6"]',
    ativoorcadocapsulareceita:'[value="68"]',
    ativoorcamentodiferente:'.feed-activity-list > [value="61"]',
    ativopadronizacaoprescritor:'.feed-activity-list > [value="9"]',
    ativoprescritorincorreto:'.feed-activity-list > [value="7"]',
    ativoqsperrado:'.feed-activity-list > [value="66"]',
    ativoreceitailegivel:'.feed-activity-list > [value="62"]',
    ativosemtitulo:'[value="114"]',
    ativotempomaior:'[value="109"]',
    ativotipocapsula:'.feed-activity-list > [value="3"]',
    ativovarejoorcadoerrado:'.feed-activity-list > [value="53"]',
    ativovarejoorcadov:'.feed-activity-list > [value="52"]',
    ativodoseerrado:'.feed-activity-list > [value="71"]',
    backoffice:'#erros > :nth-child(5) > .ibox-title > .ibox-tools > .collapse-link',
    clientecienteativofalta:'[value="112"]',
    naoinformadoformula:'[value="116"]',
    enviadocontatoerrado:'[value="115"]',
    receitavencida:'.feed-activity-list > [value="63"]',
    registrar:'#btnSubmitConferencia',


    selecionarobsatendimento:'#edit-atendimento > .col-sm-8 > .form-control',
    sucessmessage:'.toast-close-button',
    apagarobsatendimento1:':nth-child(1) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento2:':nth-child(2) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento3:':nth-child(3) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento4:':nth-child(4) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento5:':nth-child(5) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento6:':nth-child(6) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento7:':nth-child(7) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento8:':nth-child(8) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento9:':nth-child(9) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento10:':nth-child(10) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento11:':nth-child(11) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento12:':nth-child(12) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento13:':nth-child(13) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento14:':nth-child(14) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento15:':nth-child(15) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento16:':nth-child(16) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento17:':nth-child(17) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento18:':nth-child(18) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento19:':nth-child(19) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento20:':nth-child(20) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento21:':nth-child(21) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento22:':nth-child(22) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento23:':nth-child(23) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento24:':nth-child(24) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento25:':nth-child(25) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento26:':nth-child(26) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento27:':nth-child(27) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento28:':nth-child(28) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento29:':nth-child(29) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento30:':nth-child(30) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento31:':nth-child(31) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento32:':nth-child(32) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento33:':nth-child(33) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento34:':nth-child(34) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento35:':nth-child(35) > :nth-child(4) > .confirmDelete > .fa',
    apagarobsatendimento36:':nth-child(36) > :nth-child(4) > .confirmDelete > .fa',
    okapagarobsatendimento:'.modal-footer > .btn-danger',
    salvarobsatendimento:'#edit-atendimento > div.col-sm-2 > .btn',

    outrainformacao:'#outro',
    salvaroutrainformacao:'#edit-atendimento-outro > div.col-sm-2 > .btn',

    sincronizaratendimento:'#bt-sincroniza-orcamento > .fa',

    acessartrackcingatendimento:'.form-group > a',
    resultadosporpaginatracking:'class="form-select form-select-sm"',
    atualizartracking:'[id="reload"]',
    pesquisartracking:'[class="form-control form-control-sm"]',
    visualizartracking:'[btn btn-sm btn-sm]',
    pagemeusorcamentos:'[class="breadcrumb-item"]',

    acessarprepararemailatendimento:'#choose-email-form > div.col-sm-2 > .btn',
    emailpara:':nth-child(1) > .col-sm-10 > .form-control',
    emailassunto:':nth-child(3) > .col-sm-10 > .form-control',
    emailenviar:'#email-atendimento > :nth-child(3) > .btn-primary',

    acessarprepararwhatsappatendimento:'#choose-whatsapp-form > div.col-sm-2 > .btn',
    linkwhatsapp:'center > a',
    paranumerowhats:':nth-child(4) > .col-sm-7 > .form-control',
    mensagemwhatsapp:'.col-sm-7 > #content',
    personalizoumensagemwhats:'.col-sm-7 > label > input',
    copiarmensagemwhats:'[onclick="copiaMensagemWhatsapp()"]',
    okcopiarmensagemwhats:'#modal-placeholder-lg-content > .modal-footer > .btn-primary',
    cancelarmensagemwhats:'#modal-placeholder-lg-content > .modal-footer > [data-dismiss="modal"]',

    acessavaliacaoatendimento:'#link-avaliacao-form > div.col-sm-2 > .btn',
    linkavaliacao:'#modal-placeholder-lg-content > .modal-body > a',
    mensagemlinkavaliacao:'#mensagem',
    copiarmensagemlinkavaliacao:'.row > :nth-child(3) > .btn > .fa',
    fecharlinkavaliacao:'#modal-placeholder-lg-content > .modal-footer > .btn',

    acessaplicardebitoatendimento:'#creditoApplyBtn',
    debitoatendimento:'#debitoAtendimentoInput',
    ajustarcreditoatendimento:'#creditoAjusteBtn',
    acessadicionarcreditoatendimento:'#creditoAddBtn',
    creditoatendimento:'#addCreditoInput',
    aplicarcredito:'#creditoDisponivelApplyBtn',
    cancelarcredito:'#creditoDisponivelCancelBtn',

    acesstrocarresponsavelatendimento:'#atendente',

    acessgerarpagamentoatendimento:'#bt-pagamento-modal',
    paragerarpagamento:':nth-child(1) > .col-sm-10 > .form-control',
    assuntogerarpagamento:':nth-child(3) > .col-sm-10 > .form-control',
    linkcreditogerarpagamento:'#geraPagamentoCartao',
    linkpixgerarpagamento:'#geraPagamentoPix',
    processarpedidogerarpagamento:'#btnProcessarPedido',
    textoemailgerarpagamento:'#email-atendimento > :nth-child(2)',
    cancelarenvioemailgerarpagamento:'#email-atendimento > :nth-child(3) > .btn-white',
    enviaremailgerarpagamento:'#email-atendimento > :nth-child(3) > .btn-primary',

    acessconfirmaratendimento:'#bt-confirma-modal',
    orcamentista:'#orcamentista',
    tempotratamento:'#customTime',
    formapagamento:'.col-sm-7 > .small-right-space',
    orcamentoescolhido:'label > .small-right-space',
    tempopacientepoderepetir:':nth-child(4) > .col-sm-7 > .form-control',
    naoecontinuacaooutrotratamento:'.col-sm-7 > :nth-child(2) > input',
    naorealizarmonitoramento:':nth-child(6) > .col-sm-7 > input',
    salvarformapagamentorepeticao:'#confirmacao-atendimento > .modal-footer > .btn-primary',
    inserirtempotratamento:'.large-input',
    cancelartempotratamento:'#customTimeModal > .modal-dialog > .modal-content > .modal-footer > .btn-white',
    salvartempotratamento:'#saveByCustomTimeFormula',
    canalfechamentopedido:'[style="display: "] > :nth-child(1) > .col-sm-7 > .form-control',
    enviaremailrastreamento:':nth-child(2) > .col-sm-7 > .small-right-space',
    liberarpedidoinclusao:':nth-child(3) > .col-sm-7 > .small-right-space',
    liberarpedidocaixa:':nth-child(4) > .col-sm-7 > .small-right-space',
    obscaixabalcao:':nth-child(5) > .col-sm-7 > .form-control',
    notadetalhada:':nth-child(6) > .col-sm-7 > .small-right-space',
    pago:':nth-child(7) > .col-sm-7 > :nth-child(2) > .small-right-space',
    naopago:'#pago',
    endereco:'.enderecosCli',
    obsexpedicao:':nth-child(9) > .col-sm-7 > .form-control',
    formaenvio:':nth-child(10) > .col-sm-7 > .small-right-space',
    juntocom:'#juntocom',
    juntocomhigashi:':nth-child(13) > .col-sm-7 > .small-right-space',
    prometidopara:':nth-child(14) > .col-sm-7 > .form-control',
    aromashake:'[name="aromass"]',
    aromacaps:':nth-child(16) > .col-sm-7 > .form-control',
    obsgerais:':nth-child(17) > .col-sm-7 > .form-control',
    possuireceita:':nth-child(18) > .col-sm-7 > :nth-child(1) > .small-right-space',
    pedidourgente:':nth-child(20) > .col-sm-7 > .small-right-space',
    previsualizar:'#preview',
    fecharprevisualizar:'#modal-preview-lg-content > .modal-footer > .btn',
    salvarpreencheramarelinha:'#submit',

    acessencerraratendimento:'id="bt-rejeicao-modal"',
    opcaoencerraratendimento:'#motivosRejeicao',
    motivoencerraratendimento:'#motivo_enceramento_outro > .form-control',
    salvarencerraratendimento:'#rejeicao-atendimento > .modal-content > .modal-footer > .btn-primary',

}
  